name: Release

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:    
    name: Build
    if: "contains(github.event.head_commit.message, 'Release Upload')"    
    steps:
      - name: Get current date        
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{steps.date.outputs.date}}
          files: |
            eve-market-track-win32-x64.zip
