name: Release

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:    
    name: Create Release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Release Upload')"    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            builds/eve-market-track-win32-x64.zip
